### ISSUE TITLE
ValueError: cannot use LOCALE flag with a str pattern

### ISSUE THREAD

**Issue by YuchengXia** [araith/pyDEA#1]
Hi, when I run the project on terminal  with command line 'python -m pyDEA.main_gui', raise the error "ValueError: cannot use LOCALE flag with a str pattern".  And also it doesn't respond with command line 'pyDEA'.  I don't know where the problem is.  I'm now using python 3.6.4. Is it the problem? Thank you.

Response with command 'python -m pyDEA.main_gui'

Traceback (most recent call last):
  File "F:\Anaconda\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "F:\Anaconda\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "F:\Anaconda\lib\site-packages\pyDEA\main_gui.py", line 15, in <module>
    from pyDEA.core.utils.run_routine import RunMethodGUI
  File "F:\Anaconda\lib\site-packages\pyDEA\core\utils\run_routine.py", line 4, in <module>
    import xlwt
  File "F:\Anaconda\lib\site-packages\xlwt\__init__.py", line 5, in <module>
    from .Row import Row
  File "F:\Anaconda\lib\site-packages\xlwt\Row.py", line 9, in <module>
    from . import ExcelFormula
  File "F:\Anaconda\lib\site-packages\xlwt\ExcelFormula.py", line 8, in <module>
    from . import ExcelFormulaParser, ExcelFormulaLexer
  File "F:\Anaconda\lib\site-packages\xlwt\ExcelFormulaLexer.py", line 55, in <module>
    VERBOSE+LOCALE+IGNORECASE)
  File "F:\Anaconda\lib\re.py", line 233, in compile
    return _compile(pattern, flags)
  File "F:\Anaconda\lib\re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "F:\Anaconda\lib\sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)
  File "F:\Anaconda\lib\sre_parse.py", line 865, in parse
    p.pattern.flags = fix_flags(str, p.pattern.flags)
  File "F:\Anaconda\lib\sre_parse.py", line 832, in fix_flags
    raise ValueError("cannot use LOCALE flag with a str pattern")
ValueError: cannot use LOCALE flag with a str pattern

**Comment by YuchengXia** [comment]
Thank you! @olga-perederieieva
